[options]
addons_path = /mnt/extra-addons/aura_odoo_19,/usr/lib/python3/dist-packages/odoo/addons
data_dir = /var/lib/odoo
db_host = db
db_port = 5432
db_user = odoo
db_name = odoo
; No listar/crear otras bases desde la web
dbfilter = ^odoo$
list_db = False
; Cambiar esta contraseña
admin_passwd = cambiar_esto_master
proxy_mode = False
workers = 2
limit_time_cpu = 600
limit_time_real = 1200
